version: "2.2"
services:

  # Kafka Cluster
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    container_name: kafka

  # ZooKeeper Cluster
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    container_name: zookeeper

  # Flink Cluster
#  flink-job-manager:
#    image: flink:1.12.0-scala_2.11
#    expose:
#      - "6123"
#    ports:
#      - "8081:8081"
#    command: jobmanager
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#    container_name: flink_job_manager
#
#  flink-task-manager:
#    image: flink:1.12.0-scala_2.11
#    expose:
#      - "6121"
#      - "6122"
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    links:
#      - "jobmanager:jobmanager"
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#    container_name: flink_task_manager

  # Data generator

  # Flink job
  flink-job:
    build: ./flink-job/
    depends_on:
      - "kafka"
    container_name: flink_job